#
# https://github.com/tutumcloud/haproxy
# https://hub.docker.com/_/nginx/
# https://hub.docker.com/_/php/
#

redis:

  container_name: redis
  image: redis

  ports:
    - "6379:6379"


load_balancer:

  container_name: load_balancer
  image: tutum/haproxy

  links:
    - web_1
    - web_2

  ports:
    - "8080:80"


web_1:
  
  build: .
  dockerfile: nginx.Dockerfile

  volumes:
    - "./laravel:/var/www"

  links:
    - "php_1:fpm"
    
  ports:
    - "8081:80"

    
web_2:
  
  build: .
  dockerfile: nginx.Dockerfile

  volumes:
    - "./laravel:/var/www"

  links:
    - "php_2:fpm"
    
  ports:
    - "8082:80"

php_1:

  build: .
  dockerfile: fpm.Dockerfile

  volumes:
    - "./laravel:/var/www"
    - "./etc/php-fpm.dev.conf:/usr/local/etc/php-fpm.conf"

  links:
    - redis


php_2:

  build: .
  dockerfile: fpm.Dockerfile

  volumes:
    - "./laravel:/var/www"
    - "./etc/php-fpm.dev.conf:/usr/local/etc/php-fpm.conf"
    
  links:
    - redis

    
cli:

  container_name: cli

  build: .
  dockerfile: cli.Dockerfile
  
  volumes:
    - "./laravel:/var/www"
    
  links:
    - redis