#
# https://github.com/tutumcloud/haproxy
# https://hub.docker.com/_/nginx/
# https://hub.docker.com/_/php/
#


load_balancer:

  container_name: load_balancer
  image: tutum/haproxy

  links:
    - web_1
    - web_2

  ports:
    - "8080:80"


web_1:
  
  build: .
  dockerfile: nginx.Dockerfile

  volumes:
    - "./laravel:/var/www"

  links:
    - "php_1:fpm"
    
  ports:
    - "8081:80"

php_1:

  build: .
  dockerfile: fpm.Dockerfile

  volumes:
    - "./laravel:/var/www"
    
web_2:
  
  build: .
  dockerfile: nginx.Dockerfile

  volumes:
    - "./laravel:/var/www"

  links:
    - "php_2:fpm"
    
  ports:
    - "8082:80"

php_2:

  build: .
  dockerfile: fpm.Dockerfile

  volumes:
    - "./laravel:/var/www"